export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  ABOUT:"About",
  REGISTER: "Register",
  URL:"Tmth",
  FB:"Fb",
  YTB:"Yt",
  PAYMENT:"PaymentDetails",
  OTHER:"Other",
  MSGDTS:"MessageDetails",
  DURL:"Durl",
  OFFICIAL:"Official",
});
